// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  image_grid: dynamic(() => import("./ImageGrid")),
  product_details: dynamic(() => import("./ProductDetails")),
  rich_text: dynamic(() => import("./RichText")),
};
