// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  category_banner: dynamic(() => import("./CategoryBanner")),
  featured_products: dynamic(() => import("./FeaturedProducts")),
  hero: dynamic(() => import("./Hero")),
  image_banner: dynamic(() => import("./ImageBanner")),
  image_grid: dynamic(() => import("./ImageGrid")),
  product_details: dynamic(() => import("./ProductDetails")),
  rich_text: dynamic(() => import("./RichText")),
  section_title: dynamic(() => import("./SectionTitle")),
};
